 CFLAGS := -m32
LDFLAGS := -m32
ASFLAGS := --32

libbrtos.a: bedrock.o sys.o driver.o rtos.o
	$(AR) cr $@ $^

# This is an example program.
rtos_app: libbrtos.a bedrock.h rtos_app.c
	$(CC) $(CFLAGS) -L. -lbrtos rtos_app.c -o rtos_app
