parsing-parses/%.v: src/%.v
	$(Q)mkdir -p $(dir $@)
	$(VECHO) "CP $*"
	$(Q)sed s'/ADTSynthesis\./ParsingParses./' "$<" > "$@"

parsing-parses/Makefile: parsing-parses/_CoqProject
	cd parsing-parses && "$(COQBIN)"coq_makefile -f _CoqProject -o Makefile

parsing-parses/README:
	echo "This project compiles with Coq 8.4pl5, and probably other versions of Coq 8.4." > $@

pre-create-parsing-parses:
	$(MAKE) clean
	rm -rf parsing-parses
	mkdir parsing-parses
	echo "-R . ParsingParses" > parsing-parses/_CoqProject
	$(MAKE) parsers-base | tee -a parsing-parses/_CoqProject.in
	cat parsing-parses/_CoqProject.in | grep '^COQC ' | sed s'|^COQC src/||g' >> parsing-parses/_CoqProject

create-parsing-parses:
	$(Q)$(MAKE) $(addprefix parsing-parses/,$(filter %.v, $(shell cat parsing-parses/_CoqProject))) parsing-parses/Makefile parsing-parses/README
	rm parsing-parses/_CoqProject.in

do-package-parsing-parses:
	$(VECHO) TAR
	$(Q)tar -czvf parsing-parses.tar.gz parsing-parses

test-package-parsing-parses:
	$(MAKE) -C parsing-parses

package-parsing-parses:
	$(MAKE) pre-create-parsing-parses
	$(MAKE) create-parsing-parses
	$(MAKE) do-package-parsing-parses
	$(MAKE) test-package-parsing-parses

clean::
	rm -f parsing-parses.tar.gz
	rm -rf parsing-parses
