.PHONY: all test-ab-star-pretty test-ab-star test-ab-star-profile test-ab-star-profile-graph

all: test-ab-star-pretty

test-ab-star::
	$(MAKE) -f Makefile.ab_star test

test-ab-star-pretty::
	$(MAKE) -f Makefile.ab_star test-pretty

test-ab-star-profile::
	$(MAKE) -f Makefile.ab_star test-profile

test-ab-star-profile-graph::
	$(MAKE) -f Makefile.ab_star test-profile-graph
